### ISSUE TITLE
Python wrapper for tdaem1d_shrlib

### ISSUE THREAD

**Issue by leonfoks** [GeoscienceAustralia/ga-aem#1]
Hi Ross,
Does a python wrapper exist for the AEM 1D forward modelling library?

Thanks!

**Comment by rcb547** [comment]
Hi Leon 

There is a python wrapper on the develop branch. If you want a sneak peak ">>git checkout develop". I expect to merge it onto master by Monday 20160530.

Ross

**Comment by leonfoks** [comment]
Hi Ross,
Thank you! This is really great!
I pulled the develop branch and compiled successfully. However when I try running skytem_example.py I get the following "dynamic module does not define module export function (PyInit_gatdaem1d)"
I am quite new to glueing python and cpp so apologies if this is a simple issue!
Thanks!
Leon

**Comment by rcb547** [comment]
Hi Leon

If you are on linux, you will need to change the name of the loaded library to .so from .dll in https://github.com/GeoscienceAustralia/ga-aem/blob/develop/python/gatdaem1d/__init__.py. 

#libname = os.path.dirname(os.path.realpath(**file**)) + "/gatdaem1d.so";
libname = os.path.dirname(os.path.realpath(**file**)) + "\gatdaem1d.dll";

Also note this module will need Python3.

Ross

On 28 May 2016, at 02:38, Leon Foks notifications@github.com wrote:

Hi Ross,
Thank you! This is really great!
I pulled the develop branch and compiled successfully. However when I try running skytem_example.py I get the following "dynamic module does not define module export function (PyInit_gatdaem1d)"
I am quite new to glueing python and cpp so apologies if this is a simple issue!
Thanks!
Leon

**Comment by leonfoks** [comment]
Hi Ross,
I carried out both of those steps before importing the module into python. It still produces the PyInit error. 
Thanks!
Leon
