### ISSUE TITLE
Predicted Data

### ISSUE THREAD

**Issue by newexco-kv** [GeoscienceAustralia/ga-aem#11]
Hi,
Sometimes when I set Predicted Data = yes, the program doesn't run. Can this be fixed please.

**Comment by rcb547** [comment]
Hi

Can you please send a small sample data and control file pleSe.

Ross

**Comment by newexco-kv** [comment]
Hi Ross,

Here are the files.

Thanks,

[Git_AEM.zip](https://github.com/GeoscienceAustralia/ga-aem/files/6065926/Git_AEM.zip)

**Comment by rcb547** [comment]
Issue fixed in v2.0.0-Release-20240424
