### ISSUE TITLE
missing fftw in when loading DLL from Matlab on linux

### ISSUE THREAD

**Issue by cultpenguin** [GeoscienceAustralia/ga-aem#5]
When I compile GA-AEM on Linux(Ubuntu 19.10), I cannot load the DLL from Matlab using gatdaem1d_loadlibrary.m , as I get the error: 
`
Error using loadlibrary
There was an error loading the library "/ga-aem/matlab/bin/linux/gatdaem1d.so"
/ga-aem/matlab/bin/linux/gatdaem1d.so: undefined symbol: fftw_execute

Error in gatdaem1d_loadlibrary (line 5)
        [notfound warnings] = loadlibrary(libname, headerfile);
`

however, changing line 15 in gatdaem1d_matlab.make from
`libs       = -L$(FFTW_DIR)-lfftw3`
to 
`libs       = -L$(FFTW_DIR) -lfftw -lfftw3`

fixes the problem.

Have a nice day
- Thomas

**Comment by rcb547** [comment]
Issue fixed in v2.0.0-Release-20240424
